wb-mqtt-serial-templates/config-wb-mr3.json
=> Template for WB-MR3 relay module series

debian/changelog, wb-mqtt-serial.schema.json
Signed-off-by: Nikita webconn Maslov <wkernelteam@gmail.com>
=> schema: add frame_timeout_ms field for devices

debian/changelog, serial_device.cpp, serial_device.h, test/configs/config-collision-test.json, test/configs/config-no-collision-test.json, test/modbus_test.cpp, test/serial_client_test.cpp
=> remove id collision for different ports

debian/changelog, wb-mqtt-serial-templates/config-wb-mrm2-mini.json
New template for wb-mrm2-mini  modules
=> add  wb-mrm2-mini template

debian/changelog, wb-mqtt-serial-templates/config-ddm845r.json
Add razumdom ddm845R dimmer temlate
=> add ddm845r template

debian/changelog, debian/wb-mqtt-serial.init
Add start dependency on hw-conf-manager
=> Add dependency on hw-conf-manager

debian/changelog, wb-mqtt-serial-templates/config-wb-mcm8.json
=> add wb-mcm8 template

debian/changelog, wb-mqtt-serial-templates/config-wbio-ai-dv-12-20ma.json
Add wbio-ai-dv-12-20ma template
=> add wbio-ai-dv-12-20ma

README.md, debian/changelog, wb-mqtt-serial-templates/config-pzem-016.json, wb-mqtt-serial-templates/config-pzem.json
Device: https://aliexpress.ru/item/32862049796.html
=> Added template for Peacefair energy meter (PZEM)

debian/changelog, debian/control, test/iec_test.cpp
=> GMock is removed to simplify build with old wbdev

debian/changelog, wb-mqtt-serial.schema.json
Добавил путь, чтобы homeui подгружал пользовательские шаблоны
=> User templates loading in homeui is fixed

debian/changelog, wb-mqtt-serial-templates/config-wb-m1w2-di.json, wb-mqtt-serial-templates/config-wb-m1w2.json, wb-mqtt-serial-templates/config-wb-mai2-cc.json, wb-mqtt-serial-templates/config-wb-mir.json, wb-mqtt-serial-templates/config-wb-mir_simple.json, wb-mqtt-serial-templates/config-wb-mir_v2.json, wb-mqtt-serial-templates/config-wb-ms-thls-v2.json, wb-mqtt-serial-templates/config-wb-ms-thls.json, wb-mqtt-serial-templates/config-wb-ms_v2.json, wb-mqtt-serial-templates/config-wb-msw2.json, wb-mqtt-serial-templates/config-wb-msw_v3.json
By default they have 1byte + 8 ms frame timeout
=> Better compatibility with firmwares 4.16.0/4.16.1

Jenkinsfile, debian/control
* add Jenkinsfile
* add Homepage field to debian/control
=> pipeline builds

debian/changelog
for refactoring of WB-MSW v.3 templates using groups and parameters
=> increase version

debian/changelog, wb-mqtt-serial-templates/config-wb-msw_v3.json
Order of parameters and channels was changed in similar way like before adding parameters
=> MSWv3 parameters and channels order was changed

debian/changelog, src/confed_schema_generator.cpp
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/229
=> Support for parameter description in device templates

README.md, debian/changelog, src/config_merge_template.cpp, src/serial_config.cpp, src/serial_device.h, src/serial_port_driver.cpp, test/TConfigParserTest.Parse.dat, test/TSerialClientIntegrationTest.OffValue.dat, test/configs/config-test.json, test/configs/parse_test.json, test/serial_client_test.cpp, test/serial_config_test.cpp, wb-mqtt-serial.schema.json
It defines a value written to register after receiving of "0" in "on" topic
=> off_value is added to channel's config

debian/changelog, wb-mqtt-serial.schema.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/240
=> guard_interval_us description for web-interface is updated

test/serial_port_test.cpp
Give more time to flood thread to fill port's input buffer with gardage data.
=> TestImxBug fix

wb-mqtt-serial-templates/config-danfoss-ekc-202d-wb-ref.json
Correction values of Backlight Mode (o38) parameter
=> Danfoss ekc 202d template correction

debian/changelog, wb-mqtt-serial.schema.json
В прошлые коммиты не попал кусок схемы
=> Energomera CE102M config vaidation is fixed

debian/changelog, wb-mqtt-serial.schema.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/272
=> "Delete last array item" buttons are removed from homeui

debian/changelog, wb-mqtt-serial.schema.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/270
=> More accurate port parameters editors layout for homeui

debian/changelog, wb-mqtt-serial.schema.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/271
=> Shorter port type names

wb-mqtt-serial-templates/config-danfoss-ekc-204a1-wb-ref.json
Не получилось считать из контроллера EKC 204А1 регистр 1036  (Defrosting Active), читал как 11036. Удалил его из шаблона.
=> Danfoss EKC 204A1/AK-CC 210 template

debian/changelog, wb-mqtt-serial.schema.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/284
=> Uniform captions for addresses

debian/changelog, src/modbus_common.cpp, src/register_handler.cpp, src/serial_client.cpp, test/TSerialClientIntegrationTest.OnTopicWriteError.dat, test/TSerialClientIntegrationTest.ReconnectOnPortWriteError.dat, test/configs/reconnect_test_ebadf.json, test/fake_serial_device.cpp, test/fake_serial_port.cpp, test/fake_serial_port.h, test/serial_client_test.cpp
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/275
=> Improved write error handlig

debian/changelog, src/serial_config.cpp
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/300
=> Error message about duplicate device addresses is updated

debian/changelog, debian/control, src/confed_config_generator.cpp, src/confed_json_generator.cpp, src/confed_schema_generator.cpp, wb-mqtt-serial.schema.json
* default values are removed from JSON sent to web interface
* new editor format is added to poll_interval JSON schema
=> poll_interval editing in homeui is changed

debian/changelog, src/serial_config.cpp, test/TConfigParserTest.Parse.dat
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/347
=> Do not add channel's name to resulting name if it has id set to ""

debian/changelog, src/confed_json_generator.cpp, src/confed_schema_generator.cpp, wb-mqtt-serial.schema.json
Numbers are converted to strings
=> Number editor for slave_id is removed

debian/changelog, test/TDeviceTemplatesTest.Validate.dat, wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
=> Added WB-MRGBW-D fw3 template

debian/changelog, src/confed_config_generator.cpp, src/confed_json_generator.cpp, src/confed_schema_generator.cpp, src/config_schema_generator.cpp, src/json_common.cpp, src/json_common.h, wb-mqtt-serial.schema.json
* schema is changed to use wb-multiple and collapsible-list editors from json-editor
* schema of device for homeui is changed, nested object with device name hash is removed
=> "Collapse all items" button in devices list

debian/changelog, test/TDeviceTemplatesTest.Validate.dat, wb-mqtt-serial-templates/config-wb-mrwm2.json
=> WB-MRWM2 template backport to wb-2201

debian/changelog, test/TDeviceTemplatesTest.Validate.dat, wb-mqtt-serial-templates/config-map12e-fw2.json, wb-mqtt-serial-templates/config-map3e-fw2.json, wb-mqtt-serial-templates/config-map3et.json, wb-mqtt-serial-templates/config-map3ev.json, wb-mqtt-serial-templates/config-map6s-fw2.json, wb-mqtt-serial-templates/config-wb-m1w2.json, wb-mqtt-serial-templates/config-wb-mao4.json, wb-mqtt-serial-templates/config-wb-mcm8.json, wb-mqtt-serial-templates/config-wb-mdm3.json, wb-mqtt-serial-templates/config-wb-mir_v2.json, wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json, wb-mqtt-serial-templates/config-wb-mrgbw-d.json, wb-mqtt-serial-templates/config-wb-ms_v2.json, wb-mqtt-serial-templates/config-wb-msw_v3.json, wb-mqtt-serial-templates/config-wb-mwac.json
По заданию Никиты Куликова добавил каналы температуры и напряжения микроконтроллера в шаблоны устройств (кроме MAI и MIO - там еще нет поддержки этих регистров).
=> Channels MCU Temperature and MСU Voltage in templates

Makefile, debian/changelog, tools/template-generator.py
Добавил в очистку удаление шаблонов, которые делаются через jinja. Иначе make не перегенерирует их.
=> Template replacement by jinja2 is fixed

README.md, debian/changelog, src/confed_schema_generator_with_groups.cpp, src/config_schema_generator.cpp, src/config_schema_generator.h, src/serial_config.cpp, test/TConfigParserTest.UnsuccessfulParse.dat, test/configs/unsuccessful/unsuccessful-11.json, test/configs/unsuccessful/unsuccessful-12.json, test/configs/unsuccessful/unsuccessful-13.json, test/parser_test/templates/with-conditions.json, test/parser_test/templates/with-duplicate-params.json, test/serial_config_test.cpp, wb-mqtt-serial-device-template.schema.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/431
=> Parameters specified as an array in device templates

debian/changelog, template-templates/config-ecodim-dali-gw2.json.jinja
Исправил ошибку в поле "units"
=> Units correction in DALI GW2 template

Makefile, debian/changelog
Добавила строчку в мейкфайл, чтобы устанавливался файл со схемой rpc запроса
=> Install rpc request schema

wb-mqtt-serial-templates/config-t13-frequency.json
Добавил шаблон китайского частотника
Задача отсюда: https://wirenboard.bitrix24.ru/workgroups/group/14/tasks/task/view/49190/
для https://wirenboard.com/wiki/T13-400W-12-H#%D0%92%D1%8B%D0%B1%D0%BE%D1%80_%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0
=> Add template T13 VFD

debian/changelog, wb-mqtt-serial-templates/config-wbio-di-dr-14.json, wb-mqtt-serial-templates/config-wbio-di-dr-16.json, wb-mqtt-serial-templates/config-wbio-di-dr-8.json, wb-mqtt-serial-templates/config-wbio-di-wd-14.json
Добавил переводы в шаблоны модулей WBIO, чтобы закрыть задачу по переводам.
=> Russian translations in WBIO modules templates

debian/changelog, test/TDeviceTemplatesTest.Validate.dat, wb-mqtt-serial-templates/config-wbe2-i-ebus.json, wb-mqtt-serial-templates/config-wbe2-i-opentherm.json
Добавил новые каналы для поддержки прошивки в модуле OpenTherm. Для обоих модулей добавил канал управления нагревом в режиме работы с внешним датчиком и убрал параметр из сетап-секции, а также добавил переводы в оба шаблона. Вроде, сломаться ничего не должно при обновлении шаблонов. Проверил - при обновлении ошибок не возникло.
=> New channels and russian translations in OpenTherm and eBus modules templates

Makefile, debian/changelog, src/config_merge_template.cpp, src/config_merge_template.h, src/expression_evaluator.cpp, src/expression_evaluator.h, src/file_utils.cpp, src/main.cpp, src/register.cpp, src/register.h, src/serial_config.cpp, src/serial_config.h, src/serial_port.cpp, test/channel_value_test.cpp, test/expressions_test.cpp
Переделал работу с файлами на std::filesystem.
=> Changed methods for working with files and directories

debian/changelog, src/serial_port.cpp
Очень много спамит при сканировании.
=> Suppress excessive serial port logging on Info log level

Makefile, test/bin_utils_test.cpp, test/poll_plan_test.cpp
Note: the target is `feature/58788-events` (integration branch).
=> Add tests (scheduler, bin_utils)

debian/changelog, templates/config-wb-msw_v4.json
Максим проверил, что не появилось ошибок опроса
=> Decrease MSW v.4 response and frame timeouts

debian/changelog, templates/config-wb-msw_v4.json
Бэкпорт пр Петра, за исключением строки с включением continious_read
=> Decrease MSW v.4 response and frame timeouts (#586)

debian/changelog, src/devices/milur_device.cpp, src/file_descriptor_port.cpp, src/iec_common.cpp, src/modbus_common.cpp, src/modbus_common.h, src/modbus_ext_common.cpp, src/modbus_ext_common.h, src/port.h, test/modbus_ext_common_test.cpp
Выделенная протокольная часть из https://github.com/wirenboard/wb-mqtt-serial/pull/587
=> Add ext modbus proto

debian/changelog, templates/config-map12h-basic.json, templates/config-map12h-fw2-all-harmonics.json, templates/config-map12h-fw2-basic.json, templates/config-map12h-fw2-harmonics.json, templates/config-map12h-fw2.json
Исправил отсутствующие группы в шаблонах "l*"->"general"
=> fix wrong group templates MAP12_1

debian/changelog, test/fake_serial_port.cpp, test/serial_client_test.cpp
Remove old database to prevent test from reading values from previous test
=> Fix build tests

debian/changelog, templates/config-map12e-fw2.json, templates/config-map3e-fw2.json, templates/config-map3et.json, templates/config-map6s-fw2.json
Добавлено отключение логики обнуления измеренных значений тока и напряжения
=> Add disable meas correction reg to map3e-fw2

debian/changelog, templates/config-akko.json, test/TDeviceTemplatesTest.Validate.dat
It is not tested
Протестировать нет возможности, таких моторов не достать. Документация в этом месте противоречивая. Протестируем - вернём
=> Remove AKKO venetian blinds motors support

debian/changelog, src/register.h, src/serial_client_events_reader.cpp, src/serial_config.cpp, templates/config-wb-msw_v3.json, templates/config-wb-msw_v4.json, test/TPollTest.SemiSporadicRegister.dat, test/poll_test.cpp, wb-mqtt-serial.schema.json
Добавил параметр регистра `semi-sporadic`. Для таких регистров будет попытка включить события, но из цикла опроса они не будут исключаться. Опрос будет проводиться согласно обычным настройкам, так что можно задать период.
=> Add semi-sporadic register parameter

debian/changelog, src/serial_client_register_poller.cpp, test/TSerialClientIntegrationTest.ReconnectAfterNetworkDisconnect.dat, test/configs/reconnect_test_network.json, test/serial_client_test.cpp
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/664
=> Fix port reopen after connection errors (#664)

debian/changelog, wb-mqtt-serial.schema.json
Add missed in https://github.com/wirenboard/wb-mqtt-serial/pull/538 translation:
=> JSON schema: add missed translation

debian/changelog, src/confed_schema_generator.cpp, src/confed_schema_generator.h, src/confed_schema_generator_with_groups.cpp
Забыл добавлять сигнатуры в схемы для шаблонов с `subdevices`
=> Add support for device signatures in templates with subdevices

debian/changelog, debian/control, templates/config-wb-m1w2-buttons.json.jinja
Когда что то бекпортируется, на гитхабе создается новый latest релиз в котором могут быть старые шаблоны, поправила косячные, проверку из мастера не бекпортировали
=> Backport m1w2 template fix and template check

Makefile, debian/changelog, debian/rules, debian/wb-mqtt-serial.wb-mqtt-serial-templates.path, debian/wb-mqtt-serial.wb-mqtt-serial-templates.service, src/confed_config_generator.cpp, src/confed_json_generator.cpp, src/confed_schemas_map.cpp, src/confed_schemas_map.h, src/config_schema_generator.cpp, src/files_watcher.cpp, src/files_watcher.h, src/main.cpp, src/rpc_config_handler.cpp, src/serial_config.cpp, src/templates_map.cpp, src/templates_map.h, test/device_templates_file_extension_test.cpp, test/fake_serial_port.cpp, test/fake_serial_port.h, test/serial_config_test.cpp
1. Схемы для стандартных шаблонов теперь генерятся при сборке
2. Для шаблонов из /etc схемы перегенерируются при изменении.
3. Перегенерируется только одна изменившаяся схема, что занимает миллисекунды
4. Всё делает wb-mqtt-serial
=> Reload templates after changing

debian/changelog, templates/config-sokol-m.json
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/724
=> Fix SOKOL-M template (#724)

debian/changelog, wb-mqtt-serial-confed-common.schema.json
json-editor для устройств с subdevices рисовал редактор адреса внизу страницы. Немного поправил схему, чтоб рисовал как надо
=> Fix slave_id propertyOrder

debian/changelog, templates/config-map3e-fw2.json, templates/config-map3et.json, templates/config-map3ev.json
Я не ошибся, все 3 имеют одну и ту же модель в регистрах
=> Add device signature to MAP3E, MAP3ET, MAP3EV templates

config.json.wb8, debian/changelog, debian/wb-mqtt-serial.postinst
=> Add default config for wb8

Makefile, config.json.wb8, debian/changelog, debian/wb-mqtt-serial.postinst
* https://github.com/wirenboard/wb-mqtt-serial/pull/743
* https://github.com/wirenboard/wb-mqtt-serial/pull/744
=> wb-2404: Add default config for wb8

Makefile, debian/changelog, debian/rules, debian/wb-mqtt-serial.wb-mqtt-serial-templates.path, debian/wb-mqtt-serial.wb-mqtt-serial-templates.service, src/confed_config_generator.cpp, src/confed_json_generator.cpp, src/confed_schemas_map.cpp, src/confed_schemas_map.h, src/config_schema_generator.cpp, src/files_watcher.cpp, src/files_watcher.h, src/main.cpp, src/rpc_config_handler.cpp, src/serial_config.cpp, src/templates_map.cpp, src/templates_map.h, test/device_templates_file_extension_test.cpp, test/fake_serial_port.cpp, test/fake_serial_port.h, test/serial_config_test.cpp
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/722
=> Reload templates after changing (#722)

debian/changelog, templates/config-wb-m1w2-buttons.json.jinja
Добавил сигнатуру для m1w2 v.3
=> add new signature in m1w2 template

debian/changelog, templates/config-onokom-air-aux-1-mb-b.json, templates/config-onokom-air-dk-1-mb-b.json, templates/config-onokom-air-gr-1-mb-b.json, templates/config-onokom-air-hr-1-mb-b.json, templates/config-onokom-air-hs-3-mb-b.json, templates/config-onokom-air-me-1-mb-b.json
Fix warnings:
```
WARNING: [conventions] unsupported unit type "°C"
```
=> ONOKOM templates: fix units

debian/changelog, groups.json
Add "g-leakage": "Leakage protection systems" group
=> Feature/int-104 add g-leakage group

debian/changelog, templates/config-wb-led.json.jinja
[Тикет](https://wirenboard.youtrack.cloud/issue/FW-656/Bagreport-nekorrektnaya-rabota-WB-LED)
=> fix RGB Strip Hue

debian/changelog, templates/config-sokol-m.json
Из https://www.fmeter.ru/download/_ftp/meteo-kontrol/sokol-m/%D0%9F%D0%B0%D1%81%D0%BF%D0%BE%D1%80%D1%82%20%D0%B8%20%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F%20%D0%BF%D0%BE%20%D0%BC%D0%B5%D1%82%D0%B5%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B8%20%D0%A1%D0%9E%D0%9A%D0%9E%D0%9B-%D0%9C.pdf
> Диапазон измерений температуры воздуха, °С: от - 60 до + 55
> ...
> слово 2 байта - температура знаковое разрешение 0,01 град. Значение “2457” равно 24,57 град.
=> Fix SOKOL-M template

debian/changelog, templates/config-somfy-transmitter.json
[Баг-репорт](https://wirenboard.youtrack.cloud/issue/INT-189)
Канал "Stop 3" был в группе №2(ошибочно).
Канал "Stop 3" был перенесён в группу №3.
=> Fix somfy transmitter template

debian/changelog, src/modbus_common.cpp
Add compatibility with signed char
=> Fix reading strings from Modbus registers

debian/changelog, src/modbus_common.cpp, src/register.cpp, src/register.h, test/fake_serial_device.cpp
Добавил префикс `0x` и ведущие нули в лог.
=> Fix modbus register value log

debian/changelog, src/modbus_ext_common.cpp, src/modbus_ext_common.h, src/serial_client_events_reader.cpp
Убрал логи об отключении опроса регистров.
=> Fix serial client event log

debian/changelog, src/serial_config.cpp, src/serial_config.h
* поправил аргументы метода LoadRegisterConfig (убрал context)
* перенес метод LoadRegisterConfig в глобальную область видимости
=> Refactor LoadRegisterConfig method

debian/changelog, templates/config-wb-mir_v2_buttons.json.jinja, templates/config-wb-mir_v3.json.jinja
Добавлены регистры режима безопасности для WB-MIR
=> WB-MIR: Add safety mode

debian/changelog, test/device_load_config_test.cpp, test/device_templates_file_extension_test.cpp, test/serial_config_test.cpp, test/test_utils.cpp, test/test_utils.h
=> Refactor test templates features

.gitignore, debian/changelog, src/devices/curtains/somfy_sdn_device.cpp, src/devices/curtains/somfy_sdn_device.h, templates/config-somfy-sdn.json, test/somfy_test.cpp, wb-mqtt-serial-confed-common.schema.json
В https://github.com/wirenboard/wb-mqtt-serial/pull/761 изменили команду установки позиции c 0x04 на 0x07, но мотор может использоваться и как рулонный. Нужна настройка режима.
=> Somfy SDN: add application mode property

debian/changelog, templates/config-map12e-fw2.json.jinja, templates/config-map12h-fw2-all-harmonics.json, templates/config-map12h-fw2-basic.json, templates/config-map12h-fw2-harmonics.json, templates/config-map12h-fw2.json, templates/config-map3e-fw2.json, templates/config-map6s-fw2.json
Добавлены значения по умолчанию для Turns и Phi
=> WB-MAP templates: Add default values for Turns and Phi

Jenkinsfile
включаем проверку покрытия при сборке и сборку на powerhouse
=> Enable coverage

wb-mqtt-serial-ports.schema.json
Поправил коммертарии к параметрам
Стало понятнее
=> Fix descriptions of config parameters

src/serial_config.cpp, wb-mqtt-serial-confed-common.schema.json
Интерфейс будет рисоваться не через json-editor, а руками через React. Хочу упростить схему, чтобы не делать много работы на фронте. Старые конфиги теперь слегка модифицируем, чтобы не учитывать эти тонкости в схеме.
Ничего
Запустил тесты
=> Simplify slave_id schema

.github/CODEOWNERS
Добавил себя в `.github/CODEOWNERS` чтобы автоматически получать уведомления о новых PR.
=> Add u236 to code owners list

debian/changelog
=> fix changelog

debian/changelog, src/rpc/rpc_port_scan_serial_client_task.cpp
backport https://github.com/wirenboard/wb-mqtt-serial/pull/993
=> Fix WB-MAP SN reading (#993)

debian/changelog, templates/config-wb-led.json.jinja
backport https://github.com/wirenboard/wb-mqtt-serial/pull/1005
=> fix fader_dec_rgb address (#1005)
