wirenboard/wb-mqtt-serial

- debian/changelog
- wb-mqtt-serial-templates/config-map6s.json
Channels 1&3 and 4&6 were interchanged in the template (possibly because the register addresses were copied from map12h template, which has them in different order).
> map6s channels order fixed to fit to the applicable label

- debian/changelog
- debian/wb-mqtt-serial.init
1.40.4 is the latest version in the changelog but 1.40.3 was missing because it was in another pull request which hasn't been merged yet, so i added 1.40.3 version to this one.
> require mosquitto at startup

- debian/changelog
- wb-mqtt-serial.schema.json
set default value for response_timeout_ms to 500 ms
> prevent infinite waiting for devicereply

- debian/changelog
- wb-mqtt-serial-templates/config-wb-mao4.json
Исправил имя в файле шаблона модуля по форуму:
https://support.wirenboard.com/t/oshibka-v-nazvanii-ustrojstva-wb-mao4/5656
> Fix MAO4 name

- debian/changelog
- src/devices/energomera_iec_device.cpp
- src/devices/neva_device.cpp
- src/iec_common.cpp
- wb-mqtt-serial-templates/config-energomera-ce301.json
- wb-mqtt-serial-templates/config-neva-mt32x.json
* Timeouts for NEVA and Energomera CE301/CE303 energy meters are adjusted
* Show unprint symbols as hex values in debug messages for NEVA and Energomera
* Slave id is added to debug and error messages for NEVA and Energomera
* Timeout between session start retries for NEVA
> Timeouts for NEVA and Energomera are adjusted

- debian/changelog
- src/modbus_common.cpp
- src/register_handler.cpp
- src/serial_client.cpp
- src/serial_driver.cpp
- src/serial_port_driver.cpp
- src/serial_port_driver.h
* Request caching is added to modbus protocol
* MQTT controls caching is added
* Publishing of unchanged value control is moved to wb-mqtt-serial from libwbmqtt1. Opening libwbmqtt1 transactions is very expensive. So publishing of unchanged values control is implemented in wb-mqtt-serial to prevent unnecessary calls to libwbmqtt1.
> Performace optimizations during register polling

- debian/changelog
- src/confed_schema_generator.cpp
Page titles are removed from JSON schema for homeui in tabbed channels representation.
> Page titles are removed

- debian/changelog
- wb-mqtt-serial-templates/config-wb-mcm8.json
Reverts wirenboard/wb-mqtt-serial#213
Подумал, что надо переименовать параметры и в MCM это лучше тоже сделать. inputX=>inX
> Revert "Template MCM8 with parameters"

- debian/changelog
- wb-mqtt-serial-templates/config-wbe2-i-opentherm.json
Module WBE2-I-OPENTHERM register 211 (input) format was changed from u16 to s16
> WBE2-I-OPENTHERM register format was changed

- .gitignore
- debian/changelog
- src/config_schema_generator.cpp
- src/serial_config.cpp
- src/serial_config.h
- test/TConfigParserTest.UnsuccessfulParse.dat
- wb-mqtt-serial-device-template.schema.json
- wb-mqtt-serial.schema.json
1. При запуске не гружу все шаблоны через парсер json. Ищу название устройства в первых 5 строках файла. Выиграл больше секунды.
2. Перекомпоновал схемы проверки конфига и шаблонов так, чтобы лучше работали оптимизации проверки oneOf из новой libwbmqtt. Т.е. в каждом варианте был параметры из required и с выбором значения из enum. Тогда libwbmtt находит схему по ассоциативному массиву, а не пытается все схемы попробовать.
> Config validation time is decreased

- debian/changelog
- src/main.cpp
Comments writing settings are changed in jsoncpp 1.9.4. As a result config is sent to wb-mqtt-confed with comments. Confed can't handle comments and doesn't send config to web-interface.
> JSON generation for confed is fixed

- debian/changelog
- src/devices/energomera_iec_mode_c_device.cpp
- test/energomera_ce102m_test.cpp
- wb-mqtt-serial-templates/config-energomera-ce102m.json
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/245
* IDPAS parameter in device template
* "default" register type is used instead of "item_1" if no reg_type is specified
* correct custom channels schema
> IDPAS is added to Energomera CE102M template

- debian/changelog
- wb-mqtt-serial-templates/config-wb-ms_v2.json
Сравнил мастер и 2.7.1. У тех, шаблонов, где есть subdevices в master, только в MS v2 увидел конфликт.
> WB-MS v2 template revert to 2.7.1 state

- debian/changelog
- src/confed_schema_generator.cpp
- src/config_merge_template.cpp
- wb-mqtt-serial.schema.json
Config validator will not raise an error if protocol property set simultaneously with device_type is same as defined in template.
> Compatibility with old configs is improved.

- debian/changelog
- src/config_merge_template.cpp
- src/serial_config.cpp
- src/serial_config.h
- src/serial_device.h
- test/TConfigParserTest.Parse.dat
- test/TConfigParserTest.SameSetupItems.dat
- test/configs/parse_test_setup.json
- test/device-templates/config-setup-items.json
- test/parser_test/merge_template_res3.json
- test/parser_test/merge_template_res5.json
- test/parser_test/merge_template_res7.json
- test/serial_config_test.cpp
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/261
Setup registers in config have higher priority than setup registers with same addresses from device templates.
> Config's setup section priority is raised

- wb-mqtt-serial-templates/config-danfoss-erc-211-wb-ref.json
- wb-mqtt-serial-templates/config-danfoss-erc-213-wb-ref.json
- wb-mqtt-serial-templates/config-danfoss-erc-214-wb-ref.json
Не получилось полностью корректно управлять контроллером ERC 213 по Modbus: реле управления компрессором и вентилятором включаются и выключаются независимо от положения переключателя вкл/выкл контроллера (переключаются в зависимости от уставки и показаний датчика), статус контроллера не соответствует переключателю вкл/выкл, показания температуры некорректны и не изменяются в зависимости от выбранного типа датчика.
> Danfoss ERC 211 213 214 templates

- debian/changelog
- src/confed_json_generator.cpp
- src/config_schema_generator.cpp
- src/serial_config.cpp
Channels mentioned in config and not presented in template or not having addresses will be ignored with warning.
> Backward compatibility with previous device templates is improved

- debian/changelog
- wb-mqtt-serial-templates/config-map12e-fw2.json
- wb-mqtt-serial-templates/config-map12h-fw2-all-harmonics.json
- wb-mqtt-serial-templates/config-map12h-fw2-basic.json
- wb-mqtt-serial-templates/config-map12h-fw2-harmonics.json
- wb-mqtt-serial-templates/config-map12h-fw2.json
- wb-mqtt-serial-templates/config-map3e-fw2.json
- wb-mqtt-serial-templates/config-map3h-fw2-basic.json
- wb-mqtt-serial-templates/config-map3h-fw2-harmonics.json
- wb-mqtt-serial-templates/config-map3h-fw2.json
- wb-mqtt-serial-templates/config-map6s-fw2.json
Поправил шаблоны для WB-MAP*, чтобы Phi параметр мог принимать как отрицательные, так и положительные значения в диапазоне [-32768, 32767].
> Fixed a Phi parameter range for WB-MAP templates

- debian/changelog
- src/confed_schema_generator.cpp
Поправил генерацию схемы конфига для confed для правильного отображения названий каналов устройства, если в его шаблоне отсутствует перевод ("translations").
> 45814 Fixed incorrect display of channel name when generating scheme

- debian/changelog
- src/device_template_generator.cpp
- src/main.cpp
При возникновении ошибки во время сохранения конфига для wb-mqtt-serial, текущий конфиг затирался из-за того, что код возврата из приложения "wb-mqtt-serial -J" соответствовал успешному выполнению, даже при возникновении ошибки. 
wb-mqtt-confed не сохраняет конфиг в случае возврата из "wb-mqtt-serial -J" кода ошибки.
> Fixed error code on unsuccessful conversion from confed to config

- debian/changelog
- debian/wb-mqtt-serial.postinst
- debian/wb-mqtt-serial.wb-mqtt-serial-templates.service
- debian/wb-mqtt-serial.wb-mqtt-serial.service
При сохранении конфига `wb-mqtt-confed` перезапускал `wb-mqtt-serial`. Тот в свою очередь запускал `wb-mqtt-serial-templates`, т.к. оно было в `Wants`. В результате схема перегенерировалась каждый раз, как сохраняли конфиг через web-интерфейс.
> Regeneration of JSON schema for wb-mqtt-homeui after config saving is fixed

- debian/changelog
- src/serial_port.cpp
- src/serial_port.h
Для длинных пакетов select не срабатывает, пока не будет получено `rx_trig_bytes` байт. Это может быть больше чем заданный таймаут ожидания ответа. Добавил к таймауту время на получение этих байт.
> Read timeout calculation for WB7 is fixed

- debian/changelog
- src/devices/energomera_iec_device.cpp
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/446
> Energomera CE303 polling doesn't lead to continuous port closing and opening

- debian/changelog
- src/devices/milur_device.cpp
Убрал установку признака, подключения Милура в Prepare. Там реально нет проверки, что Милур отвечает, только посылка с нашей стороны. В результате, если Милур не отвечает, при каждом обращении считалось, что он подключен, потом шёл опрос регистров и ошибка в лог. Логи забивались ошибками.
> Show only first warning about failed connection to Milur

- debian/changelog
- debian/control
- src/confed_schema_generator_with_groups.cpp
- src/config_merge_template.cpp
- test/TConfigParserTest.ParametersAsArray.dat
- test/configs/parse_test_parameters_array.json
- test/device-templates/config-parameters-array.json
- test/serial_config_test.cpp
Parameters with same name are organized as oneOf array instead of anyOf. json-editor in homeui doesn't show validation errors for anyOf elements so oneOf is used.
> Support for wb-mqtt-homeui 2.39.2 is added

- debian/changelog
- src/serial_port.cpp
- src/serial_port.h
backport of https://github.com/wirenboard/wb-mqtt-serial/pull/450
> Read timeout calculation for WB7 is fixed (#450)

- debian/changelog
- template-templates/config-ecodim-dali-gw2.json.jinja
Уменьшил максимальное значение регистров яркости шлюза до 254. Значение 255 не изменяет яркость светильников.
> Maximum brightness was decreased to 254 in ECOdim DALI GW2 template

- debian/changelog
- test/device-templates/config-readonly-parameters.json
- wb-mqtt-serial-device-template.schema.json
Параметры с одновремеено заданными адресом и `readonly` проходили валидацию по 2 схемам из `oneOf`, что считается ошибкой валидации.
> Fix readonly parameters validation in device templates

- debian/changelog
- src/devices/modbus_device.cpp
- src/devices/modbus_device.h
- src/devices/modbus_io_device.cpp
- src/devices/modbus_io_device.h
- src/modbus_common.cpp
- src/modbus_common.h
- src/running_average.h
- test/TModbusBitmasksIntegrationTest.SingleWrite.dat
- test/modbus_test.cpp
response_timeout_ms is used in calculation of register request time in a poll scheduler. Low priority registers with request time more than 100ms are polled only during bus load balancing procedure, because the scheduler have to frequently check incoming commands queue. The load balancing procedure tries to divide bus equally between high and low priority registers. If high priority registers are polled too frequently it forces low priority register poll regardless to commands queue checking. Big response_timeout_ms values and rare high priority registers polling will lead to very long periods between low priority registers requests. In most situations real devices respose much earlier. So collect average response time to use it in request time calculation instead of response_timeout_ms. …
> Fix long read periods with big response_timeout_ms values

- debian/changelog
- test/serial_config_test.cpp
Build failed:
```
test/serial_config_test.cpp: In member function 'void TConfigParserTest::PrintConfig(PHandlerConfig)':
test/serial_config_test.cpp:71:41: error: loop variable 'it' creates a copy from type 'const std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wrange-loop-construct-Werror=range-loop-construct8;;]
71 |                         for (const auto it: device_channel->GetTitles()) {
|                                         ^~
test/serial_config_test.cpp:71:41: note: use reference type to prevent copying
71 |                         for (const auto it: device_channel->GetTitles()) {
|                                         ^~
|                                         & …
```
> Fix tests build

- debian/changelog
- templates/config-wb-led.json.jinja
- templates/config-wb-mrgbw-d-fw3.json.jinja
Везде по умолчанию "нет действия", а тут какие-то значения
> Set WB-LED and WB-MRGBWD default input actions to none

- debian/changelog
- templates/config-wb-msw_v3.json
шаблон умножал значение HOLD_REG_SPL_RC на 10, а должен делить
> change scale for SPL low-pass filter

- debian/changelog
- src/devices/lls_device.cpp
- src/devices/mercury230_device.h
- src/devices/milur_device.h
- src/main.cpp
- src/modbus_common.cpp
- src/modbus_common.h
- src/register.h
- src/register_handler.cpp
- src/rpc_handler.cpp
- src/rpc_port.h
- test/dlms_test.cpp
- test/em_integration.cpp
- test/energomera_ce102m_test.cpp
- test/energomera_test.cpp
- test/fake_serial_port.h
- test/lls_test.cpp
- test/mercury200_test.cpp
- test/mercury230_test.cpp
- test/milur_test.cpp
- test/modbus_io_test.cpp
- test/modbus_tcp_test.cpp
- test/modbus_test.cpp
- test/neva_test.cpp
- test/s2k_test.cpp
- test/uniel_test.cpp
```sh
wb-mqtt-serial> src/register.h:192:1: error: 'TRegisterConfig' defined as a class here but previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
<...>
wb-mqtt-serial> src/devices/mercury230_device.h:36:10: error: 'ConnectionSetup' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> src/devices/mercury230_device.h:37:15: error: 'CheckForException' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> src/modbus_common.h:69:18: error: 'GetPDU' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> …
```
> Fix compiler warnings

- test/TSerialClientIntegrationTest.RPCRequestTransceive.dat
В прошлом #557 забыл обновить RPCRequestTransceive тест, из-за этого [билд на мастере](https://jenkins.wirenboard.com/view/critical-builds/job/wirenboard/job/wb-mqtt-serial/job/master/293/) не прошел и релиз  не опубликовался. Поэтому тут не обновляю версию.
> Fix RPCRequestTransceive test

- debian/changelog
- src/rpc_handler.cpp
Too many "request timed out" errors while scanning ports.
> RPC: log IO errors at Debug log level

- debian/changelog
- templates/config-wb-mr6cv3.json.jinja
Safety timeout is not used if safety mode trigger != 1
> Fix safety timeout editing in wb-mqtt-homeui

- debian/changelog
- wb-mqtt-serial.schema.json
Fix reading of config with custom Modbus devices in wb-mqtt-homeui
Клиент делает произвольный составной канал в модбас устройстве, сохраняет, жмёт F5 и получает такую ошибку.
Для редактирования каналов использовали редактор `wb-multiple`. Он предназначен для схем с `oneOf`, но имеет оптимизацию. Каждая подсхема `oneOf` должна иметь первый текстовый параметр в `required` с только одним значением. Это работает хорошо для выбора типа устройства и т.п. В нашем же случае для выбора подсхемы надо делать полную валидацию. В результате homeui показывал вместо составного канала канал из одного регистра и писал ошибку.
> Fix config reading in wb-mqtt-homeui

- debian/changelog
- templates/config-wb-mcm8.json.jinja
Отключил события для счётчиков, т.к. они не включаются, если выбран режим работы 0 (это режим по умолчанию). Адекватного механизма задать это ограничение в wb-mqtt-serial нет. Он будет доступен после вливания https://github.com/wirenboard/wb-mqtt-serial/pull/599
> Disable events on input counters of WB-MCM8

- debian/changelog
- src/common_utils.cpp
- src/common_utils.h
- src/modbus_ext_common.cpp
- src/poll_plan.h
- src/port.cpp
- src/port.h
- src/serial_client.cpp
- src/serial_client.h
- src/serial_client_events_reader.cpp
- src/serial_client_events_reader.h
- src/serial_client_register_poller.cpp
- src/serial_client_register_poller.h
- src/serial_port_driver.cpp
- test/TPollTest.SingleDeviceEnableEventsError.dat
- test/TPollTest.SingleDeviceEventsAndBigReadTime.dat
- test/TPollTest.SingleDeviceSeveralRegisters.dat
- test/TPollTest.SingleDeviceSingleRegister.dat
- test/TPollTest.SingleDeviceSingleRegisterWithBigReadTime.dat
- test/TPollTest.SingleDeviceSingleRegisterWithEvents.dat
- test/TPollTest.SingleDeviceSingleRegisterWithEventsAndErrors.dat
- test/TPollTest.SingleDeviceSingleRegisterWithEventsAndPolling.dat
- test/TPollTest.SingleDeviceSingleRegisterWithEventsAndPollingWithReadPeriod.dat
- test/TPollTest.SingleDeviceSingleRegisterWithReadPeriod.dat
- test/poll_test.cpp
- test/serial_client_test.cpp
* Read at least one register every cycle if there are not devices with enabled events even if read time is bigger than MAX_POLL_TIME
* Fix calculation of total events read time. Unexpected zeroing of total read time lead to stop polling registers with big response-request times
> Fix stop polling some registers

- debian/changelog
- src/devices/curtains/dooya_device.cpp
- src/devices/curtains/somfy_sdn_device.cpp
- src/devices/curtains/windeco_device.cpp
- src/devices/dlms_device.cpp
- src/devices/em_device.cpp
- src/devices/ivtm_device.cpp
- src/devices/lls_device.cpp
- src/devices/mercury200_device.cpp
- src/devices/pulsar_device.cpp
- src/devices/s2k_device.cpp
- src/file_descriptor_port.cpp
- src/file_descriptor_port.h
- src/iec_common.cpp
- src/modbus_common.cpp
- src/modbus_common.h
- src/modbus_ext_common.cpp
- src/port.h
- src/rpc_handler.cpp
- src/rpc_request_handler.cpp
- src/serial_port.cpp
- src/serial_port.h
- src/tcp_port.cpp
- src/tcp_port.h
- test/fake_serial_port.cpp
- test/fake_serial_port.h
- test/modbus_ext_common_test.cpp
- test/modbus_tcp_test.cpp
- test/poll_test.cpp
Average response time must be counted till first received byte, but it was counted till last received byte
Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/600
> Fix average response time calculation

- config.json.default
- config.json.wb234
- config.json.wb5
- config.json.wb6
- config.json.wb67
- config.json.wb7
- debian/changelog
- test/configs/config-s2k-test.json
- test/configs/config-uniel-test.json
* Эти коментарии не несут никакой полезной информации
* Они будут выкинуты при первом же сохранении конфига через UI
* Благодаря им конфиг не является валидным JSON и многие тулзы на этом ломаются (напр. wb-mcu-fw-updater)
Before:
```sh
$ wb-mcu-fw-updater update-all
2023-06-02 01:49:04,838 Error in /etc/wb-mqtt-serial.conf
2023-06-02 01:49:04,851 Unhandled exception!
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/wb_mcu_fw_updater/update_monitor.py", line 239, in get_ports_on_driver
config_dict = json.load(open(driver_config_fname, "r", encoding="utf-8"))
File "/usr/lib/python3.9/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File …
```
> Remove comments from config files

- debian/changelog
- src/serial_port_driver.cpp
`DEBUG: [serial port driver] channel 'Input 4' of device 'wb-mcm8_196' <-- 1, error: ""`
> Minor fix debug logging

- debian/changelog
- src/file_descriptor_port.cpp
- src/modbus_common.cpp
- src/serial_client_events_reader.cpp
- src/serial_exc.cpp
- src/serial_exc.h
- test/fake_serial_port.cpp
Some old firmwares don't respond to unknown commands. So count timeout as absence of events support
> Handle timeout of enable events command

- debian/changelog
- src/modbus_common.cpp
TRegister::Intern внутри сохраняет все регистры в таблицу с ключём по устройству и настройкам. Ключ сравнивается не по содержимому объектов, а по их адресу.
Тут же каждый раз создаётся TRegisterConfig, следовательно, каждый раз новый регистр сохраняется в табличке. Табличка растёт
> Fix memory leak

- debian/changelog
- src/modbus_common.cpp
- test/TModbusTest.SkipNoiseAtPacketEnd.dat
- test/modbus_expectations.cpp
- test/modbus_expectations.h
- test/modbus_test.cpp
Do not raise timeout error when force frame timeout config parameter is enabled, but there isn't extra garbage data after device's responses
> Fix timeout with enabled force_frame_timeout parameter

- debian/changelog
- src/modbus_ext_common.cpp
Read all data if fast modbus packet is malformed. It prevents from reading garbage after future requests
Бэкпорт из тестинга
> Read all fast modbus packets

- debian/changelog
- src/serial_client.cpp
- src/serial_client_register_poller.cpp
- test/TSerialClientIntegrationTest.ReconnectAfterNetworkDisconnect.dat
- test/configs/reconnect_test_network.json
- test/serial_client_test.cpp
https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/66980/
Проблема при отключении tcp устройсва. Со стороны контроллера сокет живой, записать в него можно без ошибок, но нет ответов. Через длительное время сокет протухает. В wb-mqtt-serial есть логика про закрытие и открытие порта, если все устройства на нём не отвечают. К сожалению, я эту логику сломал, а существующие тесты не выявили ничего. Логика была завязана на объект устройства, которое опрашивается в текузем цикле. Но указатель на этот объект не передавался никуда, если былыи ошибки опроса.
Добавил ещё тест на проверку логики закрытия и открытия порта в аналогичных ситуациях.
> Fix port reopen after connection errors

- Makefile
- debian/changelog
- src/devices/milur_device.cpp
Valgrind detects an error on `TMilur32Test.MilurQuery` test:
```sh
==599== Conditional jump or move depends on uninitialised value(s)
==599==    at 0x4A04D5: std::_Function_handler<bool (unsigned char*, unsigned long), (anonymous namespace)::ExpectNBytes(unsigned long, unsigned long)::{lambda(unsigned char*, unsigned long)#1}>::_M_invoke(std::_Any_data const&, unsigned char*&&, unsigned long&&) (in /build/source/test/wb-homa-test)
==599==    by 0x564099: TFakeSerialPort::ReadFrame(unsigned char*, unsigned long, std::chrono::duration<long, std::ratio<1l, 1000000l> > const&, std::chrono::duration<long, std::ratio<1l, 1000000l> > const&, std::function<bool (unsigned char*, unsigned long)>) (in /build/source/test/wb-homa-test)
==599==    by 0x49FAA4: TEMDevice::ReadResponse(int, unsigned …
```
> Milur: fix frame boundary detection predicate

- .gitignore
- debian/changelog
- src/bin_utils.h
- src/confed_schema_generator.cpp
- src/devices/curtains/dauerhaft_device.cpp
- src/file_descriptor_port.cpp
- src/modbus_common.cpp
- src/modbus_ext_common.cpp
- src/running_average.h
- src/serial_client.cpp
- src/serial_client_register_poller.cpp
- src/serial_config.cpp
- src/serial_device.cpp
- src/tcp_port.cpp
- test/expressions_test.cpp
- test/poll_test.cpp
How-to:
```sh
$ bear -- make test
$ find src -name '*.cpp' -o -name '*.h' | xargs clang-tidy -p .
...
src/bin_utils.h:90:19: warning: shift count >= width of type [clang-diagnostic-shift-count-overflow]
value >>= 8;
^   ~
src/modbus_ext_common.cpp:100:9: note: in instantiation of function template specialization 'BinUtils::Append<std::back_insert_iterator<std::vector<unsigned char>>, unsigned char>' requested here
Append(it, startingSlaveId);
^
src/running_average.h:4:27: error: unknown type name 'size_t' [clang-diagnostic-error]
template<class ValueType, size_t WindowSize> class TRunningAverage
^
src/confed_schema_generator.cpp:318:14: warning: Value stored to 'tabs' during its initialization is never read [clang-analyzer-deadcode.DeadStores]
bool tabs = …
```
> Fix clang-tidy issues

- debian/changelog
- src/main.cpp
Логика публикации неизменившихся значений реализована и в wb-mqtt-serial, и в libwbmtt1. Это сделано, чтобы не дёргать либу на каждый чих, т.к. она жрёт ресурсы. Если настроена публикация неизменившихся значений раз в заданный интервал, то создаются 2 таймера: в либе и в wb-mqtt-serial. Может произойти такая ситуация, что таймер в wb-mqtt-serial позволяет публиковать, а таймер в либе ещё нет. Тогда реальная публикация произойдёт только при следующем истечении таймера в wb-mqtt-serial.
> Fix publishing period if publish unchanged values is allowed

- debian/changelog
- templates/config-sokol-m.json
В шаблоне использовались группы, которые не были объявлены. Старым версия wb-mqtt-homeui было плохо от такого. Быдем делать бэкпорт в wb-2401
> Fix SOKOL-M template

- debian/changelog
- src/rpc_config_handler.cpp
- src/templates_map.cpp
- src/templates_map.h
Передю идентификатор mqtt топика по умолчанию. Это нужно для организации на фронте проверки того, что топики у разных устройств не совпадают
> Add MQTT topic id to config/Load RPC response

- debian/changelog
- src/serial_client_register_poller.cpp
- src/serial_port_driver.cpp
* Reschedule sporadic registers reading on errors. The register must be read before excluding from polling. If not, current register's value will be undefined
* Handle undefined value, when clearing sporadic register read error
https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/74538/
Было 2 проблемы:
1. Регистры с событиями должны опрашиваться один раз, чтобы получить актуальное значение. Потом они исключаются из опроса, и значения меняются только по событию. Если при этом первом опросе возникала ошибка, регистр повторно не опрашивался, и его значение в программе было `Undefined`.
2. События включаются для всех регистров устройства, начинается запрос событий. Если запрос событий 10 раз подряд завершается с ошибкой, все регистры с событиями помечаются ошибкой чтения. Если …
> Fix clearing read error on sporadic registers

- debian/changelog
- src/serial_client_register_poller.cpp
- src/serial_port_driver.cpp
* Reschedule sporadic registers reading on errors. The register must be read before excluding from polling. If not, current register's value will be undefined
* Handle undefined value, when clearing sporadic register read error
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/742
> Fix clearing read error on sporadic registers (#742)

- debian/changelog
- debian/control
`/usr/lib/wb-utils/wb_env.sh` используется в postinst скрипте.
> Add missed wb-utils dependency

- debian/changelog
- src/main.cpp
- src/templates_map.cpp
* show errors in log if template became invalid after changing
* fix deletion of invalid templates from cache
Выводим ошибки разбора шаблона в лог.
При получении события об изменении шаблона сначала чистим кэш, потом пытаемся прочитать новый шаблон. Раньше сначала пытались читать. В результате старый шаблон оставался в кэше, т.к. процедура выкидывала исключение до шага очиски кэша.
> Show template validation errors in log

- debian/changelog
- src/confed_schema_generator_with_groups.cpp
Remove null options properties
При вызове `SetAndRemoveIfExists(newProp["options"], prop["options"], "show_opt_in")` создаются null-свойства `options` у `newProp` и `prop`. `prop` потом чистится, если в нём ничего нет, а `newProp` может так и остаться. Это попадает в схему, и json-editor давится на `options: null`. Добавил проверку, чтоб не оставлять таких свойств.
> Fix json-schema generation

- debian/changelog
- src/confed_schema_generator_with_groups.cpp
Remove null options properties
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/759
> Fix json-schema generation (#759)

- debian/changelog
- templates/config-wb-mir_v2.json
- templates/config-wb-msw_v3.json
- templates/config-wb-msw_v4.json
- templates/config-wb-msw_v4_lora.json
- test/TDeviceTemplatesTest.Validate.dat
Добавлены три канала в шаблоны устройств с IR:
- Воспроизведение ИК-команды из соответствующего банка ROM (Play)
- Редактирование ИК-команд (ROM) с копированием в RAM (ROM -> RAM)
- Запись в банк ИК-команд с использованием IR-приёмника (Learn)
Список устройств:
- WB-MSW v4
- WB-MSW v4-LoRa
- WB-MSW v3
- WB-MIR v2
> Add IR indirect control registers

- debian/changelog
- templates/config-apc-nmc2.json
Follow up https://github.com/wirenboard/wb-mqtt-serial/pull/782
"Managment Commands" группа не используется.
> Fix apc-nmc2 template

- debian/changelog
- templates/config-wb-mdm3-deprecated.json.jinja
При бекпорте #819 не пометили шаблон как deprecated, хотя в оригинальном #802 был помечен.
> WB-MDM3 template: fix deprecated template

- debian/changelog
- templates/config-oni-plc-w-acs-0800-imp.json.jinja
- templates/config-oni-plc-w-ema-0304.json.jinja
- templates/config-oni-plc-w-ema-06u00.json.jinja
- templates/config-oni-plc-w-emd-0706.json.jinja
- templates/config-wb-mai6.json.jinja
- templates/config-wb-mao4.json.jinja
- templates/config-wb-mcm8.json.jinja
- templates/config-wb-mr6c.json.jinja
Так как в шаблонах вендора не используются сигнатуры, при поиске выводились имена по нашей номенклатуре. Выключила сигнатуры из наших шаблонов, включила в вендорских
> Make vendor templates searchable from wb-device-manager

- configs/config.json.wb85
- debian/changelog
- debian/wb-mqtt-serial.postinst
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/847
> Add default config for Wiren Board 8.5 (#847)

- debian/changelog
- src/devices/curtains/a_ok_device.cpp
Some tabular motors can answer to any request. Lucky, they send its motor id, so we can filter them out
Backport of https://github.com/wirenboard/wb-mqtt-serial/pull/865
> Check motor id in A-OK protocol (#865)

- debian/changelog
- templates/config-wb-mrwm2.json.jinja
Изменен верхний предел напряжения по умолчанию
> WB-MRWM2: Change the default overvoltage threshold to 242V

- debian/changelog
- src/rpc/rpc_port_scan_serial_client_task.cpp
Исправил ошибку, из-за которой, при сканировании порта, для счетчиков WB-MAP некорректно считался серийный номер.
> Fix port scan WB-MAP signature check

- debian/changelog
- src/modbus_ext_common.cpp
Fix valgrind error:
```sh
==717== Conditional jump or move depends on uninitialised value(s)
==717==    at 0x57E40B: ModbusExt::IsModbusExtPacket(unsigned char const*, unsigned long) (in ./test/wb-homa-test)
==717==    by 0x57E452: ModbusExt::GetPacketStart(unsigned char const*, unsigned long) (in ./test/wb-homa-test)
==717==    by 0x57E491: std::_Function_handler<bool (unsigned char*, unsigned long), ModbusExt::ExpectFastModbus()::{lambda(unsigned char*, unsigned long)#1}>::_M_invoke(std::_Any_data const&, unsigned char*&&, unsigned long&&) (in ./test/wb-homa-test)
==717==    by 0x5E9F09: TFakeSerialPort::ReadFrame(unsigned char*, unsigned long, std::chrono::duration<long, std::ratio<1l, 1000000l> > const&, std::chrono::duration<long, std::ratio<1l, 1000000l> > const&, std::function<bool …
```
> Fix conditional jump depending on uninitialised value

- debian/changelog
- src/modbus_base.h
- src/modbus_common.cpp
- src/modbus_common.h
- src/serial_config.cpp
- src/serial_config.h
* теперь мето `Modbus::WriteRegister` вместо `TRegister` принимает `TRegisterConfig` 
* обновил отладочный лог метода `Modbus::WriteRegister`
* добавил enum `Modbus::ExceptionCode` для Моdbus исключений в ответах от устройств
* убрал повторяющийся код в методах `serial_config`, заменив его на вызовы метода `GetProtocolParams`
> Refactor Modbus::WriteRegister method

- debian/changelog
- src/modbus_common.cpp
- src/rpc/rpc_device_load_config_task.cpp
* добавил обработку `TResponseTimeoutException` для device/LoadConfig RPC
* поправил уровень легирования для `Modbus::WriteRegister` (ошибочно было изменено в https://github.com/wirenboard/wb-mqtt-serial/pull/896)
> Add TResponseTimeoutException handling for device/LoadConfig RPC

- debian/changelog
- src/rpc/rpc_config_handler.cpp
добавил обработку ошибки валидации шаблона для RPC `config/GetSchema`
> Add template validation error handling for config/GetSchema RPC

- debian/changelog
- src/rpc/rpc_device_load_config_task.cpp
- src/rpc/rpc_device_load_config_task.h
- src/rpc/rpc_port_driver_list.cpp
- src/rpc/rpc_port_load_modbus_serial_client_task.cpp
- src/rpc/rpc_port_load_modbus_serial_client_task.h
- src/rpc/rpc_port_load_raw_serial_client_task.cpp
- src/rpc/rpc_port_load_raw_serial_client_task.h
- src/rpc/rpc_port_scan_serial_client_task.cpp
- src/rpc/rpc_port_scan_serial_client_task.h
- src/rpc/rpc_port_setup_serial_client_task.cpp
- src/rpc/rpc_port_setup_serial_client_task.h
- src/serial_client.cpp
- src/serial_client.h
- src/write_channel_serial_client_task.cpp
- src/write_channel_serial_client_task.h
Передаю список устройств, который на порту опрашивается, в обработчики всяких RPC и проч, которые выполняют запросы к порту. Это понадобилось в новых RPC, а тащить из вне не хочется
> Add devices list to ISerialClientTask::Run parameters

- debian/changelog
- src/devices/curtains/a_ok_device.cpp
- src/devices/curtains/dooya_device.cpp
- src/devices/curtains/somfy_sdn_device.cpp
- src/devices/curtains/windeco_device.cpp
- src/serial_config.cpp
- src/templates_map.cpp
https://wirenboard.youtrack.cloud/issue/SOFT-5390/Migaet-sostoyanie-podklyuchennosti-motorov-shtor
В каналах были регистры с типом command и типом канала pushbutton. Чтение таких регистров всегда возвращало 1. Реального чтения не происходило. Из-за этого wb-mqtt-serial считал, что мотор есть на шине и отвечает. Если же мотора не было, сначала читалась позиция, по ошибке wb-mqtt-serial понимал, что мотора нет, потом читал ренистры command, получал ответ и считал, что мотор появился, и так по кругу.
Убрал чтение 1
Сделал каналы pushbutton WRITE_ONLY, чтобы исключить их из цикла чтения
> Fix A-OK, Dooya, Somfy and WinDeco meta/error flicker

- debian/changelog
- templates/config-komfovent.json
- templates/config-map3h-fw2-basic.json
* Remove duplicate channel from MAP3H fw2 basic template
* Remove duplicate channel from Network module PING2 for Komfovent C3/C4 template
Были абсолютно одинаковые объявления каналов. Убрал лишнее
> Remove duplicate channels from templates

- debian/changelog
- src/devices/modbus_device.cpp
- src/devices/modbus_device.h
- src/devices/modbus_io_device.cpp
- src/devices/modbus_io_device.h
- src/rpc/rpc_device_handler.cpp
- src/rpc/rpc_device_load_config_task.cpp
- src/rpc/rpc_device_load_config_task.h
- src/serial_device.cpp
- src/serial_device.h
- wb-mqtt-serial-rpc-device-load-config-request.schema.json
Добавил в RPC `Device/LoadConfig` возможность чтения настроек устройств для любых поддерживаемых протоколов (ранее поддерживался только Modbus).
> Add read parameters feature for non-Modbus devices to Device/LoadConig RPC

- debian/changelog
- templates/config-carel-pj-basic-deprecated.json
- templates/config-carel-pj-basic.json
Удалил из двух шаблонов:
config-carel-pj-basic.json
config-carel-pj-basic-deprecated.json
названия шаблона PYEZ1R05J4, т.к. он не поддерживает передачу данных. Тикет, где это исследовали https://wirenboard.youtrack.cloud/issue/FW-948 WB-REF-U-CR не работает с контроллером PYEZ1R05J4
Было:
Стало:
Поменял шаблон на контроллере, перезагрузилл confed, название поменялось, конфиг не сломался.
> Remove PYEZ1R05J4 from title

- debian/changelog
- templates/config-wb-msw_v3.json
- templates/config-wb-msw_v4.json
- templates/config-wb-msw_v4_lora.json
Добавлен безопасный режим через библиотеку libwbmcu-periph для устройств WB-MSW с ИК-приемопередатчиком.
Появились новые регистры для настройки безопасного режима.
Настраивал ИК-команду на включение телевизора при потере связи
> WB-MSW: Add safety mode for IR devices

- src/config_merge_template.cpp
- src/config_merge_template.h
- src/config_schema_generator.cpp
- src/expression_evaluator.cpp
- src/expression_evaluator.h
- src/rpc/rpc_device_load_config_task.cpp
- src/templates_map.cpp
- test/parser_test/merge_template_res10.json
- test/parser_test/merge_template_res11.json
- test/parser_test/merge_template_res13.json
- test/parser_test/merge_template_res9.json
- wb-mqtt-serial-confed-common.schema.json
- wb-mqtt-serial-device-template.schema.json
* Add condition dependencies to device template when sending it to homeui
* Fix default values in schema
__________________________________
При запросе шаблона устройства из homeui для каждого condition вычисляю и сохраняю список параметров, который в нём используется. На стороне фронта этот список используется для ускорения вычисления значения условия. Не хочу разбор условий тащить в фронт, а тут он и так делается. 
Ещё немного поправил схему, указао корректные зрачения по умолчанию, убрал лишнюю вложенность
> Add condition dependencies to device template

- debian/changelog
- templates/config-wb-ups-v3.json.jinja
в служебном регистре Charge Counter был перепутан адрес и не учитывался знак
стало работать
на железке
> templates: ups v.3: fix reg addr

- debian/changelog
- src/serial_config.cpp
* Allow to set max_unchanged_interval to 0 for publishing every read value
Разрешаем ставить max_unchanged_interval в 0, чтобы публиковать в MQTT после каждого чтения и события.
Разрешаем ставить max_unchanged_interval в 0, чтобы публиковать в MQTT после каждого чтения и события.
> Allow to set max_unchanged_interval to 0

- debian/changelog
- src/rpc/rpc_device_handler.cpp
Изменил формат ответа для RPC `device/SetPoll` (теперь вместо `null` в ответе лежит пустой объект `{}`). С ответом `null` парсер ответов в `python-mqtt-rpc` вызывает исключение вот тут:
https://github.com/wirenboard/python-mqtt-rpc/blob/06b4b048b459ea445b7b120a40482c1a59c181e2/mqttrpc/protocol.py#L272-L275
> Fix device/SetPoll RPC reply format
